#!/bin/bash

sudo add-apt-repository -y ppa:martin-frost/thoughtbot-rcm
sudo add-apt-repository -y ppa:git-core/ppa
curl -sL https://deb.nodesource.com/setup_0.12 | sudo bash -
sudo apt-get update
sudo apt-get -y install nodejs
sudo apt-get -y install rcm
sudo apt-get -y install git git-core
sudo apt-get -y install cmake
sudo apt-get -y install build-essential
sudo apt-get -y install python-dev
sudo apt-get -y install exuberant-ctags
sudo apt-get -y install zsh
sudo apt-get -y install python-software-properties

curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
sudo chsh -s `which zsh` vagrant

git clone https://github.com/f7k/dotfiles ~/.dotfiles
rcup -f

git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/vundle
vim +PluginInstall +qall

npm -g install https://github.com/f7k/instant-markdown-d
npm -g install jshint
